apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb
spec:
  addresses:
    - 192.168.139.160-192.168.139.165 # sesuaikan dengan ipspool di environment kalian
